FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Generate Prisma client using schema
RUN npx prisma generate

# Compile TypeScript
RUN npm run build

EXPOSE 5000

CMD ["node", "dist/server.js"]
